openapi: 3.0.0
info:
  title: Tshirt store API
  description: API ecommstore
  version: 1.1.0
  contact:
    email: akhan.crpt@gmail.com
    url: "http://lco.dev"
servers:

  - url: "{protocol}://localhost:5000/api/{version}"
    description: Optional server description Secure, e.g. Main (production) server
    variables:
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https
  - url: http://localhost:5000/
    description: Optional server description, e.g. Internal staging server for testing

# components:
#   securitySchemes:
#     cookieAuth:
#       type: apiKey
#       in: cookie
#       name: token
#     BearerAuth:
#       type: http
#       scheme: bearer

paths:
  /test:
    get:
      tags:
        - Home
      summary: Returns a list of send message.
      responses:
        '200':    # status code
          description: A JSON array of content
          content:
            application/json:
              schema: 
                type: string
                example: "mystring"
        '400':
          description: bad request    
  /signup:
    post:
      tags:
        - Home
      summary: Returns a list of send message.
      responses:
        '200':    # status code
          description: A JSON array of content
          content:
            application/json:
              schema: 
                type: string
                example: "mystring"
        '400':
          description: bad request    